apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autopilothub
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/autopilothub/homepage
  newTag: sha-95657506b3e80e60ff8d9c20097a64603008a4a2
